#!/bin/sh
/usr/libexec/java_home 2> /dev/null && java=`which java` || \
java="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"

echo "executable: $java"
"$java" -version

cd "$(dirname $0)" && \
"$java" -jar "HTGT.jar" -d 2>> HTGT-Debug.log && \
exit $? || status=$?

echo; echo "Das Programm wurde mit einem Fehler beendet: $status"
read -r -p "Zum Beenden die RETURN-Taste drücken..." dummy; echo
